# Generated by Django 5.1.3 on 2024-11-27 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppE', '0002_alter_guitarra_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provedor',
            name='email',
        ),
    ]
